package pathfileops


// DirTreeOp - Contains data fields used to store directory information
// generated by type DirMgr.
type DirTreeOp struct {
  CallingFunc        string
  FileOps            []FileOperationCode
  FileSelectCriteria FileSelectionCriteria
  SourceBaseDir      DirMgr
  TargetBaseDir      DirMgr
  ErrReturns         []string
}

// New - Creates, initializes and returns a new
// DirTreeOp instance.
func (dTreeOp DirTreeOp) New() DirTreeOp {
  newDTreeOp := DirTreeOp{}
  newDTreeOp.ErrReturns = make([]string, 0, 100)
  return newDTreeOp
}

